Apps/administradores/urls.py
from django.contrib import admin
from django.urls import path, include
from Apps.administradores import views
from .views import AdminView, CrearAdminView, EditarAdminView, AdministradorDetailView

app_name='administradores'
urlpatterns = [
    path('', AdminView.as_view(), name='adminapp'),
    path('crear/', CrearAdminView.as_view(), name='crearadmin'),
    path('editar/ <int:pk>' , EditarAdminView.as_view(), name='editaradmin'),
    path('ver/ <int:pk>', AdministradorDetailView.as_view(), name='veradmin'),

]

ColegioA/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Apps/administradores/models.py
from django.db import models

# Create your models here.

Apps/administradores/forms.py
from django import forms 
from .models import Administradores

class AdminForm(forms.ModelForm):
    class Meta:
        model = Administradores
        fields = '__all__'

Apps/administradores/views.py
# Create your views here.

from django.views.generic import ListView, CreateView, UpdateView, DetailView
from .models import Administradores
from .forms import AdminForm
from django.urls import reverse_lazy

class AdminView(ListView):
    model = Administradores
    template_name = 'admin.html'
    context_object_name = 'lista_administradores'

class CrearAdminView(CreateView):
    template_name = 'crearadmin.html'
    form_class = AdminForm
    success_url = reverse_lazy('administradores:adminapp')

class EditarAdminView(UpdateView):
    template_name = 'editaradmin.html'
    model = Administradores
    form_class = AdminForm
    success_url = reverse_lazy('administradores:adminapp')


class AdministradorDetailView(DetailView):
    model = Administradores
    template_name = 'veradmin.html' 

Apps/administradores/templates/admin.html
{% extends 'base.html' %}
{% block contenido %}
<h2>LISTA DE ADMINISTRADORES</h2>
<div>
    <table class="table">
        <thead>
            <tr>
                <th>NOMBRE</th>
                <th>EDAD</th>
                <th>DEPARTAMENTO</th>
                <th>ACCIONES</th>
            </tr>
        </thead>
        <tbody>
            {% for admin in lista_administradores %}
            <tr>
                <td>{{ admin.nombre }}</td>
                <td>{{ admin.edad }}</td>
                <td>{{ admin.departamento }}</td>
                <td>
                    <a href="{% url 'administradores:editaradmin' admin.id %}" class="btn btn-warning">EDITAR</a>
                    <a href="{% url 'administradores:veradmin' admin.pk %}" class="btn btn-info">VER</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<h2>CREAR ADMINISTRADOR ACA</h2>
<a href="{% url 'administradores:crearadmin' %}">CREAR</a>
{% endblock %}

Apps/administradores/templates/crearadmin.html
{% extends 'base.html' %}
{% block contenido %}

    <h1>CREAR ADMINISTRADOR</h1>
    <form method="post">
        {% csrf_token %}
        Nombre {{ form.nombre }}
        Edad {{ form.edad }}
        departamento {{ form.departamento }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'administradores:adminapp' %}">VER LISTA DE ADMINISTRADORES</a>

{% endblock %}

Apps/administradores/templates/editaradmin.html
{% extends 'base.html' %}
{% block contenido %}

    <h1>EDITAR ADMINISTRADOR</h1>
    <form method="post">
        {% csrf_token %}
        Nombre {{ form.nombre }}
        Edad {{ form.edad }}
        departamento {{ form.departamento }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'administradores:adminapp' %}">VOLVER A LA LISTA DE ADMINISTRADORES</a>

{% endblock %}

Apps/administradores/templates/veradmin.html
{% extends 'base.html' %}

{% block contenido %}
<h1>Detalles del Administrador</h1>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Nombre: {{ object.nombre }}</h5>
        <p class="card-text"><strong>Edad:</strong> {{ object.edad }}</p>
        <p class="card-text"><strong>Departamento:</strong> {{ object.departamento }}</p>
        <p class="card-text"><strong>Fecha de Creación:</strong> {{ object.creacion|date:"d/m/Y H:i" }}</p>
        <a href="{% url 'administradores:adminapp' %}" class="btn btn-primary">Volver al Listado</a>
    </div>
</div>
{% endblock %}