Apps/publicaciones/urls.py
from django.contrib import admin
from django.urls import path, include
from Apps.publicaciones import views
from .views import PubliView, CrearPubliView, EditarPubliView, PublicacionDetailView

app_name='publicaciones'
urlpatterns = [
    path('', PubliView.as_view(), name='publiapp'),
    path('/crear', CrearPubliView.as_view(), name='crearpubli'),
    path('/editar <int:pk>', EditarPubliView.as_view(), name='editarpubli'),
    path('/ver <int:pk>', PublicacionDetailView.as_view(), name='verpubli'),

]

ColegioA/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Apps/publicaciones/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Publicaciones(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=255)
    fecha_publicacion = models.DateField(blank=True, null=True)
    autor = models.CharField(max_length=255, blank=True, null=True)
    creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.titulo}"

    class Meta:
        managed = False
        db_table = 'publicaciones'

Apps/publicaciones/forms.py
from django import forms 
from .models import Publicaciones

class PubliForm(forms.ModelForm):
    class Meta:
        model = Publicaciones
        fields = '__all__'

Apps/publicaciones/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from .models import Publicaciones
from .forms import PubliForm
from django.urls import reverse_lazy

class PubliView(ListView):
    model = Publicaciones
    template_name='publicaciones.html'
    context_object_name = 'lista_publicaciones'

class CrearPubliView(CreateView):
    template_name = 'crearpubli.html'
    form_class = PubliForm
    success_url = reverse_lazy('publicaciones:publiapp')

class EditarPubliView(UpdateView):
    template_name = 'editarpubli.html'
    model = Publicaciones
    form_class = PubliForm
    success_url = reverse_lazy('publicaciones:publiapp')

class PublicacionDetailView(DetailView):
    model = Publicaciones
    template_name = 'verpublicacion.html' 

Apps/publicaciones/templates/crearpubli.html
{% extends 'base.html' %}
{% block contenido %}
    <h1>CREAR PUBLICACION</h1>
    <form method="post">
        {% csrf_token %}
        titulo {{ form.titulo }}
        fecha de publicacion  {{ form.fecha_publicacion }}
        autor {{ form.autor }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'publicaciones:publiapp' %}">VER LISTA DE PUBLICACIONES</a>

{% endblock %}

Apps/publicaciones/templates/editarpubli.html
{% extends 'base.html' %}
{% block contenido %}
    <h1>EDITAR PUBLICACION</h1>
    <form method="post">
        {% csrf_token %}
        titulo {{ form.titulo }}
        fecha de publicacion  {{ form.fecha_publicacion }}
        autor {{ form.autor }}
        <input type="submit" name="GUARDAR">
    </form>

    <a href="{% url 'publicaciones:publiapp' %}">VOLVER A LA LISTA DE PUBLICACIONES</a>

{% endblock %}

Apps/publicaciones/templates/publicaciones.html
{% extends 'base.html' %}
{% block contenido %}
<h2>LISTA DE PUBLICACIONES</h2>
<div>
    <table class="table">
        <thead>
            <tr>
                <th>TITULO</th>
                <th>FECHA DE PUBLICACION</th>
                <th>AUTOR</th>
                <th>ACCIONES</th>

            </tr>
        </thead>
        <tbody>
            {% for publi in lista_publicaciones %}
            <tr>
                <td>{{ publi.titulo }}</td>
                <td>{{ publi.fecha_publicacion }}</td>
                <td>{{ publi.autor }}</td>
                <td>
                    <a href="{% url 'publicaciones:editarpubli' publi.id %}" class="btn btn-warning">EDITAR</a>
                    <a href="{% url 'publicaciones:verpubli' publi.pk %}" class="btn btn-info">VER</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<h2>CREAR PUBLICACION</h2>
<a href="{% url 'publicaciones:crearpubli' %}">CREAR</a>
{% endblock %}

Apps/publicaciones/templates/verpublicacion.html
{% extends 'base.html' %}

{% block contenido %}
<h1>Detalles de la Publicación</h1>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Título: {{ object.titulo }}</h5>
        <p class="card-text"><strong>Fecha de Publicación:</strong> {{ object.fecha_publicacion }}</p>
        <p class="card-text"><strong>Autor:</strong> {{ object.autor }}</p>
        <p class="card-text"><strong>Fecha de Creación:</strong> {{ object.creacion|date:"d/m/Y H:i" }}</p>
        <a href="{% url 'publicaciones:publiapp' %}" class="btn btn-primary">Volver al Listado</a>
    </div>
</div>
{% endblock %}